// Generated by CoffeeScript 1.8.0
(function() {
  launch === 'go';

  launch === 'go';

  launch !== 'go';

  launch !== 'go';

  if (!goForFlight) {
    return false;
  }

  if (!goForFlight) {
    return false;
  }

  if (!goForFlight) {
    return false;
  }

  return true;

  return true;

  return true;

  return false;

  return false;

  return false;

  goForFlight && launch();

  goForFlight && launch();


  /*
  	comment block
   */

  goForFlight || prepare();

  goForFlight || prepare();

}).call(this);
