// Generated by CoffeeScript 1.8.0
(function() {
  var Person, bar, characters, foo, payDay, person, result, _i, _j, _len, _len1;

  foo = 'bar';

  bar = 'baz';

  if (foo === 10) {
    result = 'correct';
  }

  payDay = function() {
    return new Date().getDay() === 5;
  };

  payDay = function(day) {
    if (day == null) {
      day = 5;
    }
    return new Date().getDay() === day;
  };

  person = {
    legs: 2,
    hands: 2,
    fingers: 10
  };

  characters = ['Marty', 'Doc', 'Biff'];

  for (_i = 0, _len = characters.length; _i < _len; _i++) {
    person = characters[_i];
    console.log("Get %s to the time machine", person);
  }

  characters = ['Marty', 'Doc', 'Biff'];

  for (_j = 0, _len1 = characters.length; _j < _len1; _j++) {
    person = characters[_j];
    if (person !== 'Biff') {
      console.log("Get %s to the time machine", person);
    }
  }

  console.log("Get %person to the time machine", person);

  console.log("Get " + person + " to the time machine");

  $('h1').on('click', (function(_this) {
    return function() {
      return _this.someMethod();
    };
  })(this));

  Person = (function() {
    function Person(name, age) {
      this.name = name;
      this.age = age;
    }

    return Person;

  })();

  Person = (function() {
    function Person(name, age) {
      this.name = name;
      this.age = age;
    }

    Person.prototype.getBirthYear = function() {
      return new Date().getFullYear() - this.age;
    };

    return Person;

  })();

}).call(this);
